/*
**	Command & Conquer Generals Zero Hour(tm)
**	Copyright 2025 Electronic Arts Inc.
**
**	This program is free software: you can redistribute it and/or modify
**	it under the terms of the GNU General Public License as published by
**	the Free Software Foundation, either version 3 of the License, or
**	(at your option) any later version.
**
**	This program is distributed in the hope that it will be useful,
**	but WITHOUT ANY WARRANTY; without even the implied warranty of
**	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**	GNU General Public License for more details.
**
**	You should have received a copy of the GNU General Public License
**	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WorldBuilder.rc
//
#define IDPREVIEWSOUND                  3
#define IDC_PREVIEWSOUND                3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MAPDOC                      128
#define IDC_BRUSH_CROSS                 130
#define IDD_Height                      131
#define IDD_CellWidth                   132
#define IDD_NewHeightMap                133
#define IDS_SKELETON                    134
#define IDR_TOOLBAR1                    134
#define IDR_TOOLBAR2                    136
#define IDC_FLOOD_FILL_CURSOR           137
#define IDC_FLOOD_FILL                  137
#define IDC_TILE_CURSOR                 138
#define IDC_AUTO_EDGE_OUT               139
#define IDD_CELL_SLIDER                 140
#define IDD_HEIGHT_OPTIONS              141
#define IDD_BRUSH_OPTIONS               142
#define IDD_TERRAIN_MATERIAL            143
#define IDD_MOUND_OPTIONS               144
#define IDD_OBJECT_OPTIONS              145
#define IDC_EYEDROPPER                  146
#define IDD_CONTOUR_OPTIONS             146
#define IDC_PLACE_OBJECT                147
#define IDD_TERRAIN_MODAL               147
#define IDC_POINTER                     148
#define IDD_ROAD_OPTIONS                148
#define IDC_BLEND_EDGE                  149
#define IDD_NO_OPTIONS                  149
#define IDC_GROVE                       150
#define IDD_FEATHER_OPTIONS             150
#define IDD_MESHMOLD_OPTIONS            151
#define IDC_HAND_SCROLL                 152
#define IDD_MACRO_TEXTURE               152
#define IDC_ROAD                        153
#define IDD_WAYPOINT_OPTIONS            153
#define IDC_ROTATE                      154
#define IDD_GLOBAL_LIGHT_OPTIONS        154
#define IDC_MOVE_POINTER                155
#define IDD_LIGHT_OPTIONS               155
#define IDB_DownArrow                   157
#define IDI_Thumb                       160
#define IDC_MOLD_POINTER                161
#define IDC_WAYPOINT                    162
#define IDC_POLYGON                     163
#define IDC_POLYGON_PLUS                164
#define IDC_POLYGON_MOVE                165
#define IDD_OPEN_MAP                    166
#define IDC_BUILD_LIST_TOOL             166
#define IDD_SAVE_MAP                    167
#define IDD_MAPOBJECT_PROPS             168
#define IDD_PROPEDIT                    169
#define IDD_PLAYERLIST                  170
#define IDD_BUILD_LIST_PANEL            171
#define IDC_BUILD_ROTATE                172
#define IDD_SHADOW_OPTIONS              172
#define IDC_BUILD_POINTER               173
#define IDC_BUILD_MOVE                  174
#define IDD_ScriptDialog                175
#define IDD_DIALOG2                     176
#define IDD_ScriptTabWindow             177
#define IDD_ScriptConditions            178
#define IDD_ScriptActionsTrue           179
#define IDD_ScriptActionsFalse          180
#define IDD_ScriptProperties            181
#define IDD_ScriptCondition             182
#define IDD_EDIT_PARAMETER              184
#define IDD_ScriptAction                185
#define IDB_FOLDER                      186
#define IDD_EDIT_GROUP                  187
#define IDD_TEAMS_DIALOG                188
#define IDD_EDIT_COORD_PARAMETER        189
#define IDD_EDIT_OBJECT_PARAMETER       190
#define IDD_TeamIdentity                191
#define IDD_TeamReinforcement           192
#define IDD_TeamBehavior                193
#define IDD_EXPORT_SCRIPTS_OPTIONS      194
#define IDD_GROVE_OPTIONS               195
#define IDD_FENCE_OPTIONS               196
#define IDC_FENCE                       197
#define IDD_BLEND_MATERIAL              197
#define IDB_ROAD_CORNERS                199
#define IDI_ICON1                       200
#define IDC_WATER_PLUS                  202
#define IDC_WATER_MOVE                  203
#define IDC_WATER                       204
#define IDD_ADDPLAYER                   205
#define IDC_CLIFF                       207
#define IDC_SCORCH                      208
#define IDD_PICKUNIT                    210
#define IDC_CURSOR1                     211
#define IDD_BASE_BUILDING_PROPS         211
#define IDD_LOADING                     212
#define IDC_RAMP                        213
#define IDD_SCORCH_OPTIONS              214
#define IDD_RAMP_OPTIONS                215
#define IDD_LAYERSLIST                  216
#define IDI_Show                        217
#define IDI_Hide                        218
#define IDR_LAYERSLISTPOPUP             220
#define IDD_MAP_SETTINGS                221
#define IDD_REPLACEUNIT                 222
#define IDR_SCRIPTDIALOGPOPUP           223
#define IDD_WATER_OPTIONS               223
#define IDB_FOLDERSCRIPT                224
#define IDD_CAMERA_OPTIONS              225
#define IDD_CHANGE_TEAM_OWNER           226
#define IDB_WORLDBUILDERSPLASH          228
#define IDD_TeamGeneric                 229
#define IDD_IMPASSABLEOPTIONS           230
#define IDD_EULA_AGREEMENT              231
#define IDD_RULER_OPTIONS               232
#define IDD_TeamObjectProperties        233
#define IDI_Selected                    234
#define IDD_MAPOBJECT_PROPPAGE_GENERAL  235
#define IDD_MAPOBJECT_PROPPAGE_LOGICAL  236
#define IDD_MAPOBJECT_PROPPAGE_VISUAL   237
#define IDD_MAPOBJECT_PROPPAGE_UPGRADES 238
#define IDD_MAPOBJECT_PROPPAGE_SOUND    239
#define IDC_HEIGHT_COMBO                1000
#define IDC_CELL_WIDTH                  1001
#define IDC_INITIAL_HEIGHT              1002
#define IDC_Y_SIXE                      1003
#define IDC_Y_SIZE                      1003
#define IDC_HEIGHT_SNAP                 1004
#define IDC_BORDER_SIZE                 1004
#define IDC_HEIGHT_EDIT                 1005
#define IDC_SLIDER                      1006
#define IDC_RADIUS_EDIT                 1007
#define IDC_X_SIZE                      1008
#define IDC_SLIDER2                     1009
#define IDC_FEATHER_EDIT                1010
#define IDC_BUTTON1                     1011
#define IDC_TOP_LEFT                    1011
#define IDC_GlobalLightingReset         1011
#define IDC_UNIT_TYPE1_BUTTON           1011
#define IDC_CHANGE_NAME                 1011
#define IDC_COPYTEAM                    1011
#define IDC_RO_APPLY                    1011
#define IDC_APPLY_ROAD                  1011
#define IDC_APPLY_MESH                  1012
#define IDC_TOP                         1012
#define IDC_UNIT_TYPE2_BUTTON           1012
#define IDC_BROWSE                      1013
#define IDC_TOP_RIGHT                   1013
#define IDC_UNIT_TYPE3_BUTTON           1013
#define IDC_NEWPROP                     1014
#define IDC_CENTER_LEFT                 1014
#define IDC_UNIT_TYPE4_BUTTON           1014
#define IDC_NEWTEAM                     1015
#define IDC_CENTER                      1015
#define IDC_UNIT_TYPE5_BUTTON           1015
#define IDC_TERRAIN_NAME                1016
#define IDC_CENTER_RIGHT                1016
#define IDC_UNIT_TYPE6_BUTTON           1016
#define IDC_FEATHER_POPUP               1017
#define IDC_BOTTOM_LEFT                 1017
#define IDC_UNIT_TYPE7_BUTTON           1017
#define IDC_MOVE_DOWN                   1018
#define IDC_BOTTOM                      1018
#define IDC_TERRAIN_INFO                1019
#define IDC_BOTTOM_RIGHT                1019
#define IDC_IMPORT                      1019
#define IDC_MISSING_NAME                1020
#define IDC_TERRAIN_SWATCHES            1021
#define IDC_HEIGHT_POPUP                1022
#define IDC_OBJECT_NAME                 1023
#define IDC_SIZE_POPUP2                 1024
#define IDC_SLIDER1                     1025
#define IDC_SHOW_CONTOURS               1026
#define IDC_OBJECT_HEIGHT_EDIT          1027
#define IDC_ROAD_NAME                   1028
#define IDC_ROAD_TREEVIEW               1029
#define IDC_WIDTH_LABEL                 1030
#define IDC_HEIGHT_LABEL                1031
#define IDC_PSEd_Color1                 1031
#define IDC_FEATHER_LABEL               1032
#define IDC_WIDTH_LABEL3                1032
#define IDC_TERRAIN_TREEVIEW            1033
#define IDC_SLIDER3                     1034
#define IDC_SWAP_TEXTURES               1035
#define IDC_SIZE_POPUP                  1036
#define IDC_SIZE_EDIT                   1037
#define IDC_MESHMOLD_TREEVIEW           1038
#define IDC_PREVIEW                     1039
#define IDC_RADIUS_POPUP                1039
#define IDC_ANGLE_EDIT                  1040
#define IDC_RATE_EDIT                   1040
#define IDC_FB_EDIT                     1041
#define IDC_RATE_POPUP                  1041
#define IDC_FB_POPUP                    1042
#define IDC_RA_EDIT                     1043
#define IDC_GA_EDIT                     1044
#define IDC_BA_EDIT                     1045
#define IDC_RD_EDIT                     1046
#define IDC_GD_EDIT                     1047
#define IDC_BD_EDIT                     1048
#define IDC_XYZ_STATIC                  1049
#define IDC_RD_EDIT1                    1050
#define IDC_OPEN_LIST                   1051
#define IDC_GD_EDIT1                    1051
#define IDC_SAVE_MAP_EDIT               1052
#define IDC_BD_EDIT1                    1052
#define IDC_SAVE_LIST                   1053
#define IDC_FB_EDIT1                    1053
#define IDC_PROPERTIES                  1054
#define IDC_FB_POPUP1                   1054
#define IDC_KEYNAME                     1055
#define IDC_RD_EDIT2                    1055
#define IDC_VALUE                       1056
#define IDC_GD_EDIT2                    1056
#define IDC_KEYTYPE                     1057
#define IDC_BD_EDIT2                    1057
#define IDC_EDITPROP                    1058
#define IDC_FB_EDIT2                    1058
#define IDC_REMOVEPROP                  1059
#define IDC_FB_POPUP2                   1059
#define IDC_NEWPLAYER                   1060
#define IDC_EDITPLAYER                  1061
#define IDC_REMOVEPLAYER                1062
#define IDC_PLAYERS                     1063
#define IDC_ADDSKIRMISHPLAYERS          1064
#define IDC_OWNINGTEAM                  1067
#define IDC_PROPBOOL                    1068
#define IDC_SIDES_COMBO                 1069
#define IDC_BUILD_LIST                  1070
#define IDC_POWER                       1071
#define IDC_ALREADY_BUILD               1072
#define IDC_REBUILDS                    1073
#define IDC_ADD_BUILDING                1074
#define IDC_DELETE_BUILDING             1075
#define IDC_MOVE_UP                     1076
#define IDC_RADIO_TERRAIN               1077
#define IDC_EXPORT                      1077
#define IDC_RADIO_OBJECTS               1078
#define IDC_RADIO_EVERYTHING            1079
#define IDC_TIME_OF_DAY_CAPTION         1080
#define IDC_ALPHA_EDIT                  1081
#define IDC_ACTION_LIST                 1082
#define IDC_LIST1                       1100
#define IDC_TEAMS_LIST                  1100
#define IDC_VALIDTEAMLIST               1100
#define IDC_MAPOBJECT_BuildWithUpgrades 1100
#define IDC_LIST2                       1101
#define IDC_PLAYER_LIST                 1101
#define IDC_BUTTON2                     1103
#define IDC_BUTTON3                     1104
#define IDC_BUTTON4                     1105
#define IDC_BUTTON5                     1106
#define IDC_OR                          1107
#define IDC_LOAD                        1109
#define IDC_SAVE                        1110
#define IDC_SCRIPT_TREE                 1111
#define IDC_TAB1                        1112
#define IDC_SCRIPT_ACTIVE               1116
#define IDC_ONE_SHOT                    1117
#define IDC_SCRIPT_SUBROUTINE           1118
#define IDC_SCRIPT_COMMENT              1119
#define IDC_SCRIPT_DESCRIPTION          1121
#define IDC_NEW_FOLDER                  1122
#define IDC_NEW_SCRIPT                  1123
#define IDC_EDIT_SCRIPT                 1124
#define IDC_COPY_SCRIPT                 1125
#define IDC_DELETE                      1126
#define IDC_SCRIPT_NAME                 1127
#define IDC_VERIFY                      1127
#define IDC_RICH_EDIT_HERE              1128
#define IDC_PATCH_GC                    1129
#define IDC_CONDITION_TREE              1130
#define IDC_CONDITION_LIST              1130
#define IDC_EDIT_CONDITION              1131
#define IDC_CONDITION_TYPE              1132
#define IDC_CAPTION                     1133
#define IDC_COMBO                       1134
#define IDC_EDIT                        1135
#define IDC_LIST                        1136
#define IDC_NORMAL                      1137
#define IDC_HARD                        1138
#define IDC_NEW                         1139
#define IDC_COPY                        1140
#define IDC_EDIT_COMMENT                1141
#define IDC_TEAMS_TREEVIEW              1142
#define IDC_TEAM_SINGLETON              1143
#define IDC_TEAMNAME                    1144
#define IDC_MAPOBJECT_Team              1144
#define IDC_TEAMOWNER                   1145
#define IDC_MAPOBJECT_Script            1145
#define IDC_ALLIESLIST                  1146
#define IDC_MAPOBJECT_Repairable        1146
#define IDC_ENEMIESLIST                 1147
#define IDC_MAPOBJECT_IgnoreAllDistractions 1147
#define IDC_DELETETEAM                  1148
#define IDC_MAPOBJECT_Powered           1148
#define IDC_MAPOBJECT_RecruitableAI     1149
#define IDC_SelectTeamMembers           1149
#define IDC_STATICTEAMCAPTION           1150
#define IDC_MOVEUPTEAM                  1150
#define IDC_PLAYERNAME                  1151
#define IDC_MOVEDOWNTEAM                1151
#define IDC_PLAYERFACTION               1152
#define IDC_GROUP_NAME                  1153
#define IDC_ANGLE_POPUP                 1154
#define IDC_RAISE                       1155
#define IDC_LOWER                       1156
#define IDC_SCALE_EDIT                  1157
#define IDC_TEXTURE_TREEVIEW            1158
#define IDC_SCALE_POPUP                 1159
#define IDC_WAYPOINTNAME_EDIT           1160
#define IDC_RAISE_LOWER                 1161
#define IDC_WAYPOINTLABEL1_EDIT         1161
#define IDC_LR_EDIT                     1162
#define IDC_WAYPOINT_LOCATIONX          1162
#define IDC_LR_POPUP                    1163
#define IDC_WAYPOINTLABEL2_EDIT         1163
#define IDC_WAYPOINT_CAPTION            1164
#define IDC_WAYPOINT_CAPTION1           1164
#define IDC_LR_EDIT1                    1164
#define IDC_PLAYER_ATTITUDE_IN          1165
#define IDC_WAYPOINTLABEL3_EDIT         1165
#define IDC_LR_POPUP1                   1165
#define IDC_CHECK1                      1166
#define IDC_LR_EDIT2                    1166
#define IDC_DEPLOY_BY                   1166
#define IDC_WATER_POLYGON               1166
#define IDC_LIST_OF_WAYPOINT_NAMES      1166
#define IDC_MAPOBJECT_Selectable        1166
#define IDC_PRODUCTION_EXECUTEACTIONS   1166
#define IDC_PASSABLE_CHECK              1166
#define IDC_AUTO_VERIFY                 1166
#define IDC_EASY                        1167
#define IDC_CHECK2                      1167
#define IDC_LR_POPUP2                   1167
#define IDC_TRANSPORTS_EXIT             1167
#define IDC_MAKE_RIVER                  1167
#define IDC_WAYPOINT_LOCATIONY          1167
#define IDC_PLAYERISCOMPUTER            1168
#define IDC_CHECK3                      1168
#define IDC_TEAM_STARTS_FULL            1168
#define IDC_WAYPOINT_BIDIRECTIONAL      1168
#define IDC_GROUP_ACTIVE                1169
#define IDC_MAPOBJECT_Selectable2       1169
#define IDC_PLAYERDISPLAYNAME           1170
#define IDC_CHECK4                      1170
#define IDC_TRANSPORTS_RETURN           1170
#define IDC_PLAYER_ATTITUDE_OUT         1171
#define IDC_CHECK5                      1171
#define IDC_AVOID_THREATS               1171
#define IDC_WARNINGS_CAPTION            1172
#define IDC_CHECK6                      1172
#define IDC_WARNINGS                    1173
#define IDC_EDIT_X                      1174
#define IDC_EDIT_Y                      1175
#define IDC_OBJECT_TREEVIEW             1175
#define IDC_EDIT_Z                      1176
#define IDC_EDIT_TEMPLATE               1176
#define IDC_EDIT1                       1177
#define IDC_MAX                         1177
#define IDC_PERCENT_DESTROYED           1177
#define IDC_RO_WIDTH                    1177
#define IDC_MAP_TITLE                   1177
#define IDC_SPACING                     1177
#define IDC_SECONDS_EDIT                1177
#define IDC_ANGLE                       1177
#define IDC_HOME_WAYPOINT               1178
#define IDC_IDLE_FRAMES                 1178
#define IDC_MIN_UNIT1                   1179
#define IDC_MAX_UNIT1                   1180
#define IDC_UNIT_TYPE1                  1181
#define IDC_MIN_UNIT2                   1182
#define IDC_MAX_UNIT2                   1183
#define IDC_UNIT_TYPE2                  1184
#define IDC_MIN_UNIT3                   1185
#define IDC_MAX_UNIT3                   1186
#define IDC_UNIT_TYPE3                  1187
#define IDC_MIN_UNIT4                   1188
#define IDC_MAX_UNIT4                   1189
#define IDC_UNIT_TYPE4                  1190
#define IDC_MIN_UNIT5                   1191
#define IDC_MAX_UNIT5                   1192
#define IDC_UNIT_TYPE5                  1193
#define IDC_MIN_UNIT6                   1194
#define IDC_MAX_UNIT6                   1195
#define IDC_UNIT_TYPE6                  1196
#define IDC_EDIT4                       1197
#define IDC_DESCRIPTION                 1197
#define IDC_COMBO1                      1198
#define IDC_TEAM_BUILD_FRAMES           1198
#define IDC_RADIO1                      1199
#define IDC_SYSTEMMAPS                  1199
#define IDC_TeamGeneric_Script2         1199
#define IDC_PASSABLE                    1199
#define IDC_EVERY_FRAME                 1199
#define IDC_SCALE_OFF                   1199
#define IDC_MIN_UNIT7                   1200
#define IDC_RADIO2                      1200
#define IDC_USERMAPS                    1200
#define IDC_TeamGeneric_Script3         1200
#define IDC_IMPASSABLE                  1200
#define IDC_EVERY_SECOND                1200
#define IDC_SCALE_ON                    1200
#define IDC_MAX_UNIT7                   1201
#define IDC_RADIO3                      1201
#define IDC_TeamGeneric_Script4         1201
#define IDC_UNIT_TYPE7                  1202
#define IDC_RADIO4                      1202
#define IDC_TeamGeneric_Script5         1202
#define IDC_ON_CREATE_SCRIPT            1203
#define IDC_TeamGeneric_Script6         1203
#define IDC_WAYPOINTS                   1204
#define IDC_ON_IDLE_SCRIPT              1204
#define IDC_TeamGeneric_Script7         1204
#define IDC_TRIGGERS                    1205
#define IDC_ON_ENEMY_SIGHTED            1205
#define IDC_TeamGeneric_Script8         1205
#define IDC_UNITS                       1206
#define IDC_ON_DESTROYED                1206
#define IDC_TeamGeneric_Script9         1206
#define IDC_ALL_SCRIPTS                 1207
#define IDC_ON_ALL_CLEAR                1207
#define IDC_TeamGeneric_Script10        1207
#define IDC_SELECTED_SCRIPTS            1208
#define IDC_ON_UNIT_DESTROYED_SCRIPT    1208
#define IDC_TeamGeneric_Script11        1208
#define IDC_TeamGeneric_Script12        1209
#define IDC_Grove_Type1                 1210
#define IDC_TeamGeneric_Script13        1210
#define IDC_Grove_Per1                  1211
#define IDC_TeamGeneric_Script14        1211
#define IDC_Grove_Type2                 1212
#define IDC_TeamGeneric_Script15        1212
#define IDC_Grove_Per2                  1213
#define IDC_TeamGeneric_Script16        1213
#define IDC_Grove_Type3                 1214
#define IDC_Grove_Per3                  1215
#define IDC_Grove_Type4                 1216
#define IDC_Grove_Per4                  1217
#define IDC_Grove_PerTotal              1218
#define IDC_Grove_Type5                 1219
#define IDC_Grove_Per5                  1220
#define IDC_Grove_NumberTrees           1221
#define IDC_FENCE_SPACING_EDIT          1222
#define IDC_AUTO_REINFORCE              1224
#define IDC_PERIMETER_DEFENSE           1224
#define IDC_AI_RECRUITABLE              1225
#define IDC_ATTACK_COMMON_TARGET        1225
#define IDC_BASE_DEFENSE                1226
#define IDC_TEAM_NAME                   1226
#define IDC_PRODUCTION_CONDITION        1227
#define IDC_PRODUCTION_PRIORITY         1228
#define IDC_PRIORITY_INCREASE           1229
#define IDC_ENEMY_INTERACTIONS          1229
#define IDC_PRIORITY_DECREASE           1230
#define IDC_MAPOBJECT_StartingHealthEdit 1231
#define IDC_MAPOBJECT_Enabled           1232
#define IDC_MAPOBJECT_Destructible      1233
#define IDC_MAPOBJECT_Indestructible    1233
#define IDC_MAPOBJECT_Sellable          1234
#define IDC_MAPOBJECT_Whiner            1235
#define IDC_MAPOBJECT_Deployed          1236
#define IDC_MAPOBJECT_StartingHealth    1237
#define IDC_MAPOBJECT_VisionDistance    1238
#define IDC_MAPOBJECT_Aggressiveness    1239
#define IDC_MAPOBJECT_Recruitable       1240
#define IDC_MAPOBJECT_GroupNumber       1241
#define IDC_MAPOBJECT_ShroudClearingDistance 1241
#define IDC_MAPOBJECT_Name              1242
#define IDC_MAPOBJECT_Veterancy         1243
#define IDC_MAPOBJECT_ZOffset           1244
#define IDC_MAPOBJECT_Angle             1245
#define IDC_MAPOBJECT_StoppingDistance  1246
#define IDC_GROUP_SUBROUTINE            1250
#define IDC_BROAD_CURVE                 1251
#define IDC_TIGHT_CURVE                 1252
#define IDC_ANGLED                      1253
#define IDC_Grove_AllowWaterPlacement   1254
#define IDC_Grove_AllowCliffPlacement   1255
#define IDC_ANCHOR_LABEL                1256
#define IDC_JOIN                        1257
#define IDC_WATER_HEIGHT1               1258
#define IDC_WATER_HEIGHT2               1259
#define IDC_WAYPOINT_CAPTION2           1260
#define IDC_WAYPOINT_LOCATION           1260
#define IDC_WAYPOINT_CAPTION3           1261
#define IDC_WAYPOINT_PATHLABELS         1261
#define IDC_LIST_WAYPOINTS              1262
#define IDC_PlayerColor                 1263
#define IDC_PlayerColorCombo            1264
#define IDC_SCORCHTYPE                  1268
#define IDC_MAP_WEATHER                 1269
#define IDC_MAP_TIMEOFDAY               1270
#define IDC_MAP_DESCRIPTION             1271
#define IDC_MAPOBJECT_Weather           1272
#define IDC_MAP_COMPRESSION             1272
#define IDC_MAPOBJECT_Time              1273
#define IDC_MAPOBJECT_HitPoints         1274
#define IDC_LL_TREE                     1275
#define IDC_TRANSPORT_COMBO             1276
#define IDC_WAYPOINT_COMBO              1277
#define IDC_VETERANCY                   1278
#define IDC_MISSINGLABEL                1279
#define IDC_CameraReset                 1281
#define IDC_PITCH_POPUP                 1282
#define IDC_PITCH_EDIT                  1283
#define IDC_HEIGHTTEXT                  1284
#define IDC_ZOOMTEXT                    1285
#define IDC_POSTEXT                     1286
#define IDC_TARGETTEXT                  1287
#define IDC_WATERNAME_EDIT              1288
#define IDC_REPLACETHISTEXT             1289
#define IDC_COLORBUTTON                 1290
#define IDC_MAPOBJECT_Unsellable        1291
#define IDC_MAPOBJECT_Targetable        1292
#define IDC_SCRIPT_PREFIX1              1299
#define IDC_SCRIPT_PREFIX2              1300
#define IDC_SCRIPT_PREFIX3              1301
#define IDC_SCRIPT_PREFIX4              1302
#define IDC_SCRIPT_PREFIX5              1303
#define IDC_SCRIPT_PREFIX6              1304
#define IDC_SCRIPT_PREFIX7              1305
#define IDC_SCRIPT_PREFIX8              1306
#define IDC_SCRIPT_PREFIX9              1307
#define IDC_SCRIPT_PREFIX10             1308
#define IDC_SCRIPT_PREFIX11             1309
#define IDC_SCRIPT_PREFIX12             1310
#define IDC_SCRIPT_PREFIX13             1311
#define IDC_SCRIPT_PREFIX14             1312
#define IDC_SCRIPT_PREFIX15             1313
#define IDC_SCRIPT_PREFIX16             1314
#define IDC_TeamGeneric_Script1         1315
#define IDC_DROP_WAYPOINT_BUTTON        1316
#define IDC_ACTION_TREE                 1326
#define IDC_CENTER_ON_SELECTED          1327
#define IDC_CHECK_RULER                 1328
#define IDC_SIDES                       1329
#define IDC_RULER_WIDTH                 1330
#define IDC_UPDATE_TEAM_MEMBERS         1331
#define IDC_USE_TEAM_DEFAULTS           1332
#define IDC_LOOPING_CHECKBOX            1333
#define IDC_ENABLED_CHECKBOX            1334
#define IDC_CUSTOMIZE_CHECKBOX          1335
#define IDC_MAPOBJECT_Scale             1336
#define IDC_SOUND_COMBO                 1346
#define IDC_LOOPCOUNT_EDIT              1347
#define IDC_MIN_VOLUME_EDIT             1348
#define IDC_PRIORITY_COMBO              1349
#define IDC_MIN_RANGE_EDIT              1350
#define IDC_MAX_RANGE_EDIT              1351
#define IDC_VOLUME_EDIT                 1352
#define IDC_MAPOBJECT_XYPosition        1353
#define IDC_STATIC_MAPOBJECT_GENERAL    1379
#define IDC_STATIC_MAPOBJECT_LOGICAL    1380
#define IDC_STATIC_MAPOBJECT_SOUND      1381
#define IDC_STATIC_MAPOBJECT_VISUAL     1382
#define IDC_MAPOBJECT_DISTANCE          1383
#define ID_BRUSH_TOOL                   32771
#define IDM_ShowGrid                    32772
#define ID_FEATHERTOOL                  32791
#define ID_BIG_TILE_TOOL                32792
#define ID_SLIDER                       32793
#define ID_TEXTURES_0                   32800
#define ID_TEXTURES_1                   32801
#define ID_TEXTURES_2                   32802
#define ID_TEXTURES_3                   32803
#define ID_TEXTURES_4                   32804
#define ID_BRUSH_ADD_TOOL               32900
#define ID_BRUSH_SUBTRACT_TOOL          32901
#define ID_TILE_TOOL                    32902
#define ID_TILE_FLOOD_FILL              32903
#define ID_BUTTON32904                  32904
#define ID_AUTO_EDGE_OUT_TOOL           32905
#define ID_AUTO_EDGE_IN_TOOL            32906
#define ID_TS_MIP_EDGE                  32907
#define ID_TS_MIP_BASE                  32908
#define ID_TS_SUBSAMPLE                 32909
#define ID_TS_INFO                      32910
#define ID_EYEDROPPER_TOOL              32913
#define ID_TS_32X32                     32915
#define ID_TS_CANONICAL                 32916
#define ID_FILE_RESIZE                  32917
#define ID_PLACE_OBJECT_TOOL            32918
#define ID_TS_REFRESH                   32919
#define ID_POINTER_TOOL                 32921
#define ID_BLEND_EDGE_TOOL              32922
#define ID_GROVE_TOOL                   32924
#define ID_EDIT_LINK_CENTERS            32925
#define ID_VIEW_SHOW_OBJECTS            32926
#define ID_VIEW_SHOWTEXTURE             32927
#define ID_TS_REMAP                     32929
#define ID_VIEW_SHOWCONTOURS            32930
#define ID_EDIT_DELETE                  32931
#define ID_VIEW_SHOWWIREFRAME           32934
#define ID_VIEW_SHOWTERRAIN             32935
#define ID_OBJECTPROPERTIES_REFLECTSINMIRROR 32936
#define ID_ROAD_TOOL                    32937
#define ID_VIEW_TOGGLE_ROAD             32938
#define ID_VIEW_SNAPTOGRID              32939
#define ID_EDIT_SELECTDUP               32940
#define ID_OBJECTPROPERTIES_ANGLEDCORNER 32941
#define ID_VIEW_TIME_OF_DAY             32942
#define ID_VIEW_SHOWENTIRE3DMAP         32943
#define ID_VIEW_SHOWTOPDOWNVIEW         32944
#define ID_VIEW_SHOWCLOUDS              32945
#define ID_EDIT_CONTOUROPTIONS          32946
#define IDM_RESET_WINDOWS               32947
#define ID_WINDOW_PREVIEW640X480        32949
#define ID_WINDOW_PREVIEW800X600        32950
#define ID_WINDOW_PREVIEW1024X768       32951
#define ID_WINDOW_2DWINDOW              32952
#define ID_VIEW_BRUSHFEEDBACK           32954
#define ID_MOLD_TOOL                    32955
#define ID_VIEW_SHOWMACROTEXTURE        32956
#define ID_EDIT_SELECTMACROTEXTURE      32957
#define ID_RULER_TOOL                   32958
#define ID_SCRIPT_EDIT                  32959
#define ID_TEAM_EDIT                    32960
#define ID_LOCK_HORIZONTAL              32962
#define ID_LOCK_VERTICAL                32963
#define ID_WAYPOINT_TOOL                32964
#define ID_EDIT_GLOBALLIGHTOPTIONS      32965
#define ID_VIEW_SHOWWAYPOINTS           32966
#define ID_POLYGON_TOOL                 32968
#define ID_VIEW_SHOWPOLYGONTRIGGERS     32969
#define ID_EDIT_PLAYERLIST              32970
#define ID_EDIT_WORLDINFO               32971
#define ID_BUILD_LIST_TOOL              32972
#define ID_HAND_SCROLL_TOOL             32973
#define ID_VIEW_RELOADTEXTURES          32974
#define ID_EDIT_SHADOWS                 32975
#define ID_VIEW_SHOWSHADOWS             32976
#define ID_EDIT_SCRIPTS                 32977
#define ID_EDIT_TEAMLIST                32978
#define ID_FENCE_TOOL                   32979
#define ID_VIEW_SHOWIMPASSABLEAREAS     32981
#define ID_TEXTURESIZING_TILE4X4        32982
#define ID_TEXTURESIZING_TILE6X6        32983
#define ID_TEXTURESIZING_TILE8X8        32984
#define ID_WATER_TOOL                   32986
#define ID_TEXTURESIZING_MAPCLIFFTEXTURES 32987
#define ID_EDIT_SELECTSIMILAR           32988
#define ID_VIEW_PARTIALMAPSIZE_96X96    32989
#define ID_VIEW_PARTIALMAPSIZE_128X128  32990
#define ID_VIEW_PARTIALMAPSIZE_160X160  32991
#define ID_VIEW_PARTIALMAPSIZE_192X192  32992
#define ID_FILE_JUMPTOGAME              32993
#define ID_EDIT_PICKSTRUCTS             32994
#define ID_EDIT_PICKINFANTRY            32995
#define ID_EDIT_PICKVEHICLES            32996
#define ID_EDIT_PICKSHRUBBERY           32997
#define ID_EDIT_PICKMANMADE             32998
#define ID_EDIT_PICKNATURAL             32999
#define ID_EDIT_PICKDEBRIS              33000
#define ID_EDIT_PICKANYTHING            33001
#define ID_EDIT_PICKWAYPOINTS           33002
#define ID_VIEW_LABELS                  33003
#define ID_VIEW_SHOWMODELS              33004
#define ID_EDIT_SELECTINVALIDTEAM       33005
#define ID_FILE_DUMPTOFILE              33006
#define ID_SCORCH_TOOL                  33007
#define ID_VIEW_BOUNDINGBOXES           33008
#define ID_VIEW_SIGHTRANGES             33009
#define ID_VIEW_WEAPONRANGES            33010
#define ID_HIGHLIGHT_TESTART            33011
#define ID_SHOW_LETTERBOX               33012
#define ID_TEXTURESIZING_REMOVECLIFFTEXMAPPING 33014
#define ID_VIEW_LAYERS_LIST             33015
#define ID_INSERTNEWLAYER               33017
#define ID_DELETECURRENTLAYER           33018
#define ID_LAYERSLIST_MERGELAYERINTO_BOGUS 33021
#define ID_LAYERSLIST_MERGELAYERINTO_BEGIN 33022
#define ID_LAYERSLIST_MERGELAYERINTO_END 33121
#define ID_LAYERSLIST_MERGEOBJECTINTO_BOGUS 33122
#define ID_LAYERSLIST_MERGEOBJECTINTO_BEGIN 33123
#define ID_LAYERSLIST_MERGEOBJECTINTO_END 33222
#define ID_LAYERSLIST_MERGEVIEWSELECTIONINTO_BOGUS 33223
#define ID_LAYERSLIST_MERGEVIEWSELECTIONINTO_BEGIN 33224
#define ID_LAYERSLIST_MERGEVIEWSELECTIONINTO_END 33323
#define ID_HIDECURRENTLAYER             33324
#define ID_EDIT_MAPSETTINGS             33325
#define ID_VIEW_GARRISONED              33326
#define ID_EDIT_PICKROADS               33327
#define ID_SCRIPTACTIVATE               33328
#define ID_BORDERTOOL                   33330
#define ID_VIEW_SHOWMAPBOUNDARIES       33331
#define ID_TOGGLE_PITCH_AND_ROTATE      33332
#define ID_EDIT_CAMERAOPTIONS           33333
#define ID_VIEWHOME                     33334
#define ID_VIEW_SHOWSOFTWATER           33335
#define ID_VALIDATION_GENERATEMAPREPORT 33337
#define ID_VALIDATION_FIXTEAMS          33338
#define ID_VIEW_SHOWEXTRABLENDS         33339
#define ID_VIEW_SHOWAMBIENTSOUNDS       33340
#define ID_EDIT_PICKSOUNDS              33341
#define ID_VIEW_SHOW_TERRAIN            33342
#define ID_VIEW_IMPASSABLEAREAOPTIONS   33343
#define ID_SELECTLAYEROBJECT            33344
#define ID_SELECTACTIVELAYER            33345
#define ID_VIEW_SHOW_SOUND_CIRCLES      33346
#define IDS_NEW                         61446
#define IDS_RESIZE                      61447
#define IDS_REMOVING_INUSE_TEAM         61448
#define IDS_RENAMING_INUSE_TEAM         61449
#define IDS_NAME_IN_USE                 61450
#define IDS_BAD_OWNER_NAME              61451
#define IDS_OUT_OF_MEMORY               61452
#define IDS_BAD_FILE_DATA               61453
#define IDS_BAD_VALUE                   61454
#define IDS_FILE_IS_READONLY            61455
#define IDS_REPLACEFILE                 61456
#define IDS_ONLY_ONE_FILE               61457
#define IDS_NO_AUTOSAVE                 61458
#define IDS_TOO_MANY_TILES              61459
#define IDS_TOO_MANY_BLENDS             61460
#define IDS_TEXTURE_TOO_LARGE           61461
#define IDS_ALPHA_BLEND                 61462
#define IDS_SCRIPT_INFORMATION          61463
#define IDS_SCRIPT_WARNINGS             61464
#define IDS_SCRIPT_NOWARNINGS           61465
#define IDS_CONFIRM_REPLACE_TEXTURE     61466
#define ID_RAMP                         61467
#define ID_RAMPTOOL                     61467
#define IDS_CONFIRM_REMOVE_CLIFF_MAPPING 61468
#define IDS_NUM_SELECTED_ON_TEAM        61469
#define IDS_MAX_OBJECTS                 61470
#define IDS_REPLACEOWNER                61471
#define IDS_SPLASH_LOADING              61472
#define IDS_SINGLE_SELECTION_ONLY       61473
#define IDS_NO_UPGRADES                 61474
#define IDS_TEAMS_FIXED                 61475
#define IDS_EULA_AGREEMENT1             61476
#define IDS_EULA_AGREEMENT2             61477
#define IDS_EULA_AGREEMENT3             61478
#define IDS_EULA_AGREEMENT4             61479
#define IDS_EULA_AGREEMENT5             61480
#define IDS_MAPOBJECT_PROPS_TITLE       61481
#define IDS_NO_PROBLEMS                 61482
#define IDS_DUPLICATE_TEAM_REMOVED      61483
#define IDS_PLAYERLESS_TEAM_REMOVED     61484
#define IDS_NEED_TO_FIX_TEAMS           61485

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        242
#define _APS_NEXT_COMMAND_VALUE         33347
#define _APS_NEXT_CONTROL_VALUE         1354
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
