//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ParticleEditor.rc
//
#define IDD_PSEd                        1000
#define IDC_PSEd_ParticleSystem         1000
#define IDC_PSEd_Go                     1001
#define IDC_PSEd_ParentSystem           1002
#define IDD_PSEd_EditColorAndAlpha      1002
#define IDC_PSEd_EmissionType           1003
#define IDD_PSEd_EmissionPanelLine      1003
#define IDC_PSEd_AngleXMin              1004
#define IDD_PSEd_EmissionPanelSphere    1004
#define IDC_PSEd_VelocityType           1005
#define IDD_PSEd_EmissionPanelBox       1005
#define IDC_PSEd_LineStartY             1005
#define IDC_PSEd_DriftVelocityX         1005
#define IDC_PSEd_ParticleType           1006
#define IDD_PSEd_EmissionPanelCylinder  1006
#define IDC_PSEd_LineStartZ             1006
#define IDC_PSEd_SlaveOffsetX           1006
#define IDC_PSEd_ShaderType             1007
#define IDC_PSEd_LineEndX               1007
#define IDC_PSEd_AngleYMin              1008
#define IDC_PSEd_LineEndY               1008
#define IDD_PSEd_EmissionPanelPoint     1008
#define IDC_PSEd_AngleZMin              1009
#define IDC_PSEd_LineEndZ               1009
#define IDD_PSEd_VelocityPanelOrtho     1009
#define IDC_PSEd_AngularRateXMin        1010
#define IDD_PSEd_VelocityPanelSphere    1010
#define IDC_PSEd_AngularRateYMin        1011
#define IDD_PSEd_VelocityPanelHemisphere 1011
#define IDC_PSEd_AngularRateZMin        1012
#define IDD_PSEd_VelocityPanelCylinder  1012
#define IDC_PSEd_AngleXMax              1013
#define IDD_PSEd_VelocityPanelOutward   1013
#define IDC_PSEd_AngleYMax              1014
#define IDD_PSEd_ParticlePanelDrawable  1014
#define IDC_PSEd_AngleZMax              1015
#define IDD_PSEd_ParticlePanelParticle  1015
#define IDC_PSEd_AngularRateXMax        1016
#define IDD_PSEd_EditMoreParms          1016
#define IDR_FileMenu                    1016
#define IDC_PSEd_AngularRateYMax        1017
#define IDD_PSEd_EditSwitchesDialog     1017
#define IDC_PSEd_AngularRateZMax        1018
#define IDD_PSEd_ParticlePanelStreak    1018
#define IDC_PSEd_AngleDampingMin        1019
#define IDC_PSEd_DriftVelocityY         1019
#define IDC_PSEd_AngleDampingMax        1020
#define IDC_PSEd_DriftVelocityZ         1020
#define IDC_PSEd_VelocityDampingMin     1021
#define IDC_PSEd_VelocityDampingMax     1022
#define IDC_PSEd_SlaveOffsetY           1023
#define IDC_PSEd_Save                   1023
#define IDC_PSEd_Priority               1023
#define IDC_PSEd_Gravity                1024
#define IDC_PSEd_SlaveOffsetZ           1025
#define IDC_PSEd_Reload                 1025
#define IDC_PSEd_KillAll                1025
#define IDC_PSEd_SystemLifetime         1026
#define IDC_PSEd_ParticleLifetimeMin    1027
#define IDC_PSEd_ParticleLifetimeMax    1028
#define IDC_PSEd_SizeRateMin            1029
#define IDC_PSEd_SizeRateMax            1030
#define IDC_PSEd_Color1                 1031
#define IDC_PSEd_Color2                 1032
#define IDC_PSEd_Color3                 1033
#define IDC_PSEd_Color4                 1034
#define IDC_PSEd_Color5                 1035
#define IDC_PSEd_Color6                 1036
#define IDC_PSEd_Color7                 1037
#define IDC_PSEd_Color8                 1038
#define IDC_PSEd_EditColorButton        1039
#define IDC_PSEd_Continued              1040
#define IDC_PSEd_EditSwitchesButton     1041
#define IDC_EmissionProperties          1045
#define IDC_PSEd_CylRadius              1046
#define IDC_PSEd_CylLength              1047
#define IDC_PSEd_BoxHalfSizeX           1048
#define IDC_PSEd_BoxHalfSizeY           1049
#define IDC_PSEd_BoxHalfSizeZ           1050
#define IDC_PSEd_LineStartX             1051
#define IDC_PSEd_SphereRadius           1052
#define IDC_PSEd_EmissionPanel          1053
#define IDC_PSEd_CylinderRadialMax      1053
#define IDC_PSEd_VelocityPanel          1054
#define IDC_PSEd_CylinderNormalMin      1054
#define IDC_PSEd_ParticlePanel          1055
#define IDC_PSEd_CylinderNormalMax      1055
#define IDC_VelocityProperties          1057
#define IDC_PSEd_CylinderRadialMin      1059
#define IDC_PSEd_HemisphereRadialMin    1060
#define IDC_PSEd_HemisphereRadialMax    1061
#define IDC_PSEd_SphereRadialMin        1062
#define IDC_PSEd_SphereRadialMax        1063
#define IDC_PSEd_OutwardOtherMin        1064
#define IDC_PSEd_OutwardOtherMax        1065
#define IDC_PSEd_OutwardSpeedMin        1066
#define IDC_PSEd_OutwardSpeedMax        1067
#define IDC_PSEd_CF1_Frame              1068
#define IDC_PSEd_OrthoZMin              1068
#define IDC_PSEd_CF2_Frame              1069
#define IDC_PSEd_OrthoZMax              1069
#define IDC_PSEd_CF3_Frame              1070
#define IDC_PSEd_OrthoXMin              1070
#define IDC_PSEd_CF4_Frame              1071
#define IDC_PSEd_OrthoXMax              1071
#define IDC_PSEd_CF5_Frame              1072
#define IDC_PSEd_OrthoYMin              1072
#define IDC_PSEd_CF6_Frame              1073
#define IDC_PSEd_OrthoYMax              1073
#define IDC_PSEd_CF7_Frame              1074
#define IDC_PSEd_OneShot                1074
#define IDC_PSEd_CF8_Frame              1075
#define IDC_PSEd_Hollow                 1075
#define IDC_PSEd_AF1_Min                1076
#define IDC_PSEd_ParticleTypeDrawable   1076
#define IDC_PSEd_AF2_Min                1077
#define IDC_PSEd_ParticleTypeParticle   1077
#define IDC_PSEd_AF3_Min                1078
#define IDC_PSEd_BurstDelayMin          1078
#define IDC_PSEd_AF1_Max                1079
#define IDC_PSEd_BurstDelayMax          1079
#define IDC_PSEd_AF2_Max                1080
#define IDC_PSEd_InitialDelayMin        1080
#define IDC_PSEd_AF3_Max                1081
#define IDC_PSEd_InitialDelayMax        1081
#define IDC_PSEd_AF4_Min                1082
#define IDC_PSEd_BurstCountMin          1082
#define IDC_PSEd_AF5_Min                1083
#define IDC_PSEd_BurstCountMax          1083
#define IDC_PSEd_AF6_Min                1084
#define IDC_PSEd_ColorScaleMin          1084
#define IDC_PSEd_AF4_Max                1085
#define IDC_PSEd_ColorScaleMax          1085
#define IDC_PSEd_AF5_Max                1086
#define IDC_PSEd_AF6_Max                1087
#define IDC_PSEd_SlaveSystem            1087
#define IDC_PSEd_AF7_Min                1088
#define IDC_PSEd_PerParticleSystem      1088
#define IDC_PSEd_AF8_Min                1089
#define IDC_PSEd_SizeMin                1089
#define IDC_PSEd_AF7_Max                1090
#define IDC_PSEd_SizeMax                1090
#define IDC_PSEd_AF8_Max                1091
#define IDC_PSEd_SizeDampingMin         1091
#define IDC_PSEd_CurrentParticleCap     1091
#define IDC_PSEd_AF1_Frame              1092
#define IDC_PSEd_SizeDampingMax         1092
#define IDC_PSEd_CurrentParticleCount   1092
#define IDC_PSEd_AF2_Frame              1093
#define IDC_PSEd_GroundAligned          1093
#define IDC_PSEd_StartSizeRateMin       1093
#define IDC_PSEd_AF3_Frame              1094
#define IDC_PSEd_EmitAboveGroundOnly    1094
#define IDC_PSEd_StartSizeRateMax       1094
#define IDC_PSEd_AF4_Frame              1095
#define IDC_PSEd_ParticleUpTowardsEmitter 1095
#define IDC_PSEd_AF5_Frame              1096
#define IDC_PSEd_AF6_Frame              1097
#define IDC_PSEd_AF7_Frame              1098
#define IDC_PSEd_WindAngleChangeMin     1098
#define IDC_PSEd_AF8_Frame              1099
#define IDC_PSEd_WindPingPongStartAngleMin 1099
#define IDC_PSEd_WindPingPongStartAngleMax 1100
#define IDC_PSEd_WindMotion             1101
#define IDC_PSEd_WindAngleChangeMax     1102
#define IDC_PSEd_WindPingPongEndAngleMin 1103
#define IDC_PSEd_WindPingPongEndAngleMax 1104
#define ID_FILE_SAVEALL                 32771
#define ID_FILE_SAVECURRENT             32772
#define ID_FILE_RELOADCURRENT           32773
#define ID_FILE_RELOADALL               32775
#define ID_FILE_RELOADTEXTURES          32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1019
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
