//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by max2w3d.rc
//
#define IDS_COPYRIGHT_NOTICE            1
#define IDS_AUTHOR_NAME                 2
#define IDS_GAMEMTL                     3
#define IDS_MAP_TEXTURE                 4
#define IDS_ENVMAP                      5
#define IDS_SCENE_EXPORT                6
#define IDS_LIB_DESCRIPTION             7
#define IDS_FILE_OPEN_ERROR             8
#define IDS_DLL_NAME                    9
#define IDS_WTM_SHORT_DESCRIPTION       10
#define IDS_WTM_LONG_DESCRIPTION        11
#define IDS_WHT_SHORT_DESCRIPTION       12
#define IDS_WHT_LONG_DESCRIPTION        13
#define IDS_WHA_SHORT_DESCRIPTION       14
#define IDS_WHA_LONG_DESCRIPTION        15
#define IDS_WTM_FILE_EXTEN              16
#define IDS_WHT_FILE_EXTEN              17
#define IDS_WHA_FILE_EXTEN              18
#define IDS_W3D_FILE_EXTEN              19
#define IDS_W3D_LONG_DESCRIPTION        20
#define IDS_W3D_SHORT_DESCRIPTION       21
#define IDS_W3D_UTILITY_CLASS_NAME      22
#define IDS_W3DMENU_CATEGORY            23
#define IDS_W3DMENU_TITLE               24
#define IDS_SOT                         25
#define IDS_DIFFUSE_COLOR               26
#define IDS_PARAMETERS                  27
#define IDS_TEXTURE_MAP                 28
#define IDS_ENVIRONMENT_MAP             29
#define IDS_TEXMAPS                     30
#define IDS_AM                          31
#define IDS_DI                          32
#define IDS_SP                          33
#define IDS_SH                          34
#define IDS_SS                          35
#define IDS_SI                          36
#define IDS_OP                          37
#define IDS_FI                          38
#define IDS_BU                          39
#define IDS_RL                          40
#define IDS_RR                          41
#define IDS_NONE                        42
#define IDS_NOTES                       43
#define IDD_GAMEMTL_PASS_COUNT          101
#define IDD_VOXEL_DEBUG_DIALOG          103
#define IDD_W3D_EXPORT_OPTIONS          106
#define IDD_W3D_UTILITY_DIALOG          107
#define IDD_BONE_INFLUENCE_PARAMS       108
#define IDD_SKELETON_PARAMETERS         109
#define IDD_SKIN_SOT                    110
#define IDD_GAMEMTL_PANEL               111
#define IDD_GAMEMTL_NOTES_PANEL         112
#define IDD_GAMEMTL_HINTS_PANEL         114
#define IDD_GAMEMTL_PSX_PANEL           115
#define IDD_GAMEMTL_PASS                118
#define IDD_GAMEMTL_VERTEX_MATERIAL     119
#define IDD_GAMEMTL_SHADER              120
#define IDD_GAMEMTL_TEXTURES            121
#define IDD_GAMEMTL_PASS_COUNT_DIALOG   122
#define IDD_GENERATE_NAMES_DIALOG       126
#define IDD_MESH_DEFORM_PANEL           127
#define IDI_ORIG                        127
#define IDI_DEFORMED                    128
#define IDD_GAMEMTL_SURFACE_TYPE        128
#define IDD_GAMEMTL_DISPLACEMENT_MAP    129
#define IDB_NORM                        130
#define IDB_DEFORM                      131
#define IDD_GENERATE_MTL_NAMES_DIALOG   133
#define IDD_GENERATE_LOD_EXTENSION_DIALOG 135
#define IDD_EXPORT_ALL                  136
#define IDD_SCENE_SETUP                 137
#define IDD_GAMEMTL_PS2_SHADER          138
#define IDD_GAMEMTL_PS2_TEXTURES        139
#define IDD_ALPHA_MODIFIER              140
#define IDD_W3D_LOG                     142
#define IDD_INPUT_DIALOG                143
#define IDD_W3DUTILITY_FLOATER_DIALOG   145
#define IDD_W3DUTILITY_SETTINGS_DIALOG  147
#define IDD_W3DUTILITY_TOOLS_DIALOG     148
#define IDD_W3D_EXPORT_OPTIONS1         149
#define IDD_W3D_PRESET_EXPORT_OPTIONS   149
#define IDD_EXPORT_PANE_HLOD            150
#define IDD_EXPORT_PANE_ANIMATED_HLOD   151
#define IDD_EXPORT_PANE_ANIMATION       152
#define IDD_EXPORT_PANE_MESH            153
#define IDD_EXPORT_PANE_SKELETON        154
#define IDD_EXPORT_PANE_TERRAIN         155
#define IDD_ANIMATION_COMPRESSION       156
#define IDI_DISK                        157
#define IDB_WW3D                        158
#define IDD_GRIDSNAP_PARAMS             159
#define IDC_TRANSLATION_ONLY_CHECK      1000
#define IDC_TERRAIN_MODE_CHECK          1001
#define IDC_SETPASSCOUNT                1014
#define IDC_PASSCOUNT_SPIN              1016
#define IDC_PASSCOUNT_EDIT              1017
#define IDC_MAPON_DCT                   1018
#define IDC_MAX_SETS_SPIN               1018
#define IDC_GAMEMTL_PASSCOUNT_STATIC    1019
#define IDC_MAX_SETS_EDIT               1019
#define IDC_MAPON_SCT                   1020
#define IDC_STAGE0_DISPLAY_BUTTON       1020
#define IDC_VOXEL_VIEWPORT              1021
#define IDC_MAPON_DIT                   1021
#define IDC_STAGE0_PUBLISH_BUTTON       1021
#define IDC_MAPON_SIT                   1022
#define IDC_STAGE1_DISPLAY_BUTTON       1022
#define IDC_WHT_EXPORT_RADIO            1023
#define IDC_STAGE1_PUBLISH_BUTTON       1023
#define IDC_WHT_LOAD_RADIO              1024
#define IDC_STAGE0_RESIZE_BUTTON        1024
#define IDC_WHA_EXPORT_RADIO            1025
#define IDC_STAGE0_NO_MIPMAP_BUTTON     1025
#define IDC_WHT_BROWSE_BUTTON           1026
#define IDC_STAGE0_CLAMP_U_BUTTON       1026
#define IDC_WHA_NO_EXPORT_RADIO         1027
#define IDC_STAGE0_CLAMP_V_BUTTON       1027
#define IDC_WTM_EXPORT_RADIO            1028
#define IDC_STAGE1_RESIZE_BUTTON        1028
#define IDC_WTM_NO_EXPORT_RADIO         1029
#define IDC_STAGE1_NO_MIPMAP_BUTTON     1029
#define IDC_STAGE1_CLAMP_U_BUTTON       1030
#define IDC_WHT_NO_EXPORT_RADIO         1031
#define IDC_STAGE1_CLAMP_V_BUTTON       1031
#define IDC_STAGE0_ALPHA_BITMAP_BUTTON  1032
#define IDC_LAYER_EDIT                  1033
#define IDC_RANGE_LOW_EDIT              1033
#define IDC_STAGE1_ALPHA_BITMAP_BUTTON  1033
#define IDC_RANGE_HIGH_EDIT             1034
#define IDC_NAME_INDEX_EDIT             1034
#define IDC_STAGE0_NOLOD_BUTTON         1034
#define IDC_DCT_FRAMES_EDIT             1035
#define IDC_STAGE1_NOLOD_BUTTON         1035
#define IDC_DCT_FRAMES_SPIN             1036
#define IDC_OPACITY_EDIT                1037
#define IDC_HIERARCHY_CHECK             1038
#define IDC_OPACITY_SPIN                1038
#define IDC_UNHIDE_GEOMETRY             1039
#define IDC_SCT_FRAMES_EDIT             1039
#define IDC_SELECT_ALPHA_MESHES         1039
#define IDC_LINK_BY_NAME_BUTTON         1040
#define IDC_BASE_POSE_EDIT              1040
#define IDC_UNHIDE_HIERARCHY            1040
#define IDC_SCT_FRAMES_SPIN             1040
#define IDC_SELECT_GEOMETRY             1040
#define IDC_AUTO_LINK_BUTTON            1041
#define IDC_BASE_POSE_SPIN              1041
#define IDC_HIDE_ALL                    1041
#define IDC_FOG_EDIT                    1041
#define IDC_SELECT_HIERARCHY            1041
#define IDC_ADD_BONES_BUTTON            1042
#define IDC_GEOMETRY_CHECK              1042
#define IDC_FOG_SPIN                    1042
#define IDC_LINK_BUTTON                 1042
#define IDC_REMOVE_BONES_BUTTON         1043
#define IDC_TRANSULCENCY_EDIT           1043
#define IDC_COLLECTION_NAMES_GENERATE   1043
#define IDC_UNLINK_BUTTON               1043
#define IDC_BONE_LIST                   1044
#define IDC_TRANSLUCENCY_SPIN           1044
#define IDC_COLLECTION_NAMES_INCREMENT_LOD 1044
#define IDC_SELECT_PHYSICAL             1044
#define IDC_SIT_FRAMES_EDIT             1045
#define IDC_GEOMETRY_CAMERA_ALIGNED     1045
#define IDC_SIT_FRAMES_SPIN             1046
#define IDC_GEOMETRY_CAMERA_ORIENTED    1046
#define IDC_SHININESS_EDIT              1047
#define IDC_GEOMETRY_NORMAL             1047
#define IDC_SHININESS_SPIN              1048
#define IDC_GEOMETRY_AABOX              1048
#define IDC_SELECT_PROJECTILE           1049
#define IDC_COLLISION_PHYSICAL          1050
#define IDC_DCT_RATE_EDIT               1051
#define IDC_SELECT_VIS                  1051
#define IDC_DCT_RATE_SPIN               1052
#define IDC_GEOMETRY_OBBOX              1052
#define IDC_LAYER_SPIN                  1053
#define IDC_RANGE_LOW_SPIN              1053
#define IDC_OBJ_NAME                    1053
#define IDC_DIT_FRAMES_EDIT             1053
#define IDC_RANGE_HIGH_SPIN             1054
#define IDC_DIT_FRAMES_SPIN             1054
#define IDC_NAME_INDEX_SPIN             1054
#define IDC_MATERIAL_NAMES_GENERATE     1054
#define IDC_DIT_RATE_EDIT               1055
#define IDC_GEOMETRY_SHADOW             1055
#define IDC_DIT_RATE_SPIN               1056
#define IDC_GEOMETRY_NULL               1056
#define IDC_SCT_RATE_EDIT               1057
#define IDC_LOD_EXTENSION_GENERATE      1057
#define IDC_GEOMETRY_AGGREGATE          1057
#define IDC_DCT_MAPPING_COMBO           1058
#define IDC_GEOMETRY_LIGHTGLARE         1058
#define IDC_GEOMETRY_DAZZLE             1058
#define IDC_DIT_MAPPING_COMBO           1059
#define IDC_MAPPING_COMBO               1059
#define IDC_MAPPING0_COMBO              1059
#define IDC_SCT_MAPPING_COMBO           1060
#define IDC_MAPPING1_COMBO              1060
#define IDC_SCT_RATE_SPIN               1061
#define IDC_USE_ALPHA_CHECK             1062
#define IDC_SIT_MAPPING_COMBO           1063
#define IDC_SIT_RATE_EDIT               1064
#define IDC_SIT_RATE_SPIN               1065
#define IDC_DIT_OVER_DCT_CHECK          1067
#define IDC_SIT_OVER_SCT_CHECK          1068
#define IDC_USE_SORTING_CHECK           1068
#define IDC_DIT_OVER_DIG_CHECK          1069
#define IDC_NO_TRANS                    1069
#define IDC_SIT_OVER_SIG_CHECK          1070
#define IDC_100_TRANS                   1070
#define IDC_FAST_SPECULAR_AFTER_ALPHA_CHECK 1071
#define IDC_50_TRANS                    1071
#define IDC_25_TRANS                    1072
#define IDC_MINUS_100_TRANS             1073
#define IDC_NO_RT_LIGHTING              1074
#define IDC_VIEWPORT_DISPLAY_CHECK      1075
#define IDC_COLORMASK_CHECK             1081
#define IDC_DEPTHMASK_CHECK             1082
#define IDC_ALPHATEST_CHECK             1083
#define IDC_DEPTHCOMPARE_COMBO          1085
#define IDC_DESTBLEND_COMBO             1086
#define IDC_FOG_COMBO                   1087
#define IDC_PRIGRADIENT_COMBO           1088
#define IDC_SRCBLEND_COMBO              1089
#define IDC_DETAILCOLOR_COMBO           1090
#define IDC_DETAILALPHA_COMBO           1091
#define IDC_STAGE0_HINT_COMBO           1092
#define IDC_SECGRADIENT_COMBO           1093
#define IDC_STAGE1_HINT_COMBO           1095
#define IDC_STAGE0_FRAMES_EDIT          1096
#define IDC_STAGE0_FRAMES_SPIN          1097
#define IDC_STAGE0_RATE_EDIT            1098
#define IDC_STAGE0_RATE_SPIN            1099
#define IDC_DCT_BUTTON                  1100
#define IDC_GAMEMTL_TAB                 1100
#define IDC_STAGE0_BUTTON               1101
#define IDC_SCT_BUTTON                  1102
#define IDC_STAGE1_BUTTON               1102
#define IDC_DIT_BUTTON                  1103
#define IDC_AMBIENT_COLOR               1103
#define IDC_SIT_BUTTON                  1104
#define IDC_EMISSIVE_COLOR              1104
#define IDC_SHADEMODEL_COMBO            1105
#define IDC_STAGE1_FRAMES_EDIT          1106
#define IDC_STAGE1_FRAMES_SPIN          1107
#define IDC_STAGE1_RATE_EDIT            1108
#define IDC_STAGE1_RATE_SPIN            1109
#define IDC_DITHERMASK_COMBO            1110
#define IDC_DIFFUSE_COLOR               1113
#define IDC_STAGE0_ENABLE               1113
#define IDC_SPECULAR_COLOR              1114
#define IDC_STAGE1_ENABLE               1114
#define IDC_AMBIENT_COEFF               1115
#define IDC_STAGE1_ANIM_COMBO           1115
#define IDC_DIFFUSE_COEFF               1116
#define IDC_PRESET_COMBO                1116
#define IDC_EMISSIVE_COEFF              1117
#define IDC_STAGE0_ANIM_COMBO           1117
#define IDC_SPECULAR_COEFF              1118
#define IDC_GEOMETRY_TWO_SIDED          1119
#define IDC_COLLISION_VIS               1120
#define IDC_GEOMETRY_HIDE               1121
#define IDC_GEOMETRY_ZNORMALS           1122
#define IDC_GEOMETRY_VERTEX_ALPHA       1123
#define IDC_BASE_NAME_EDIT              1124
#define IDC_GEOMETRY_CAST_SHADOW        1124
#define IDC_PREFIX_EDIT                 1125
#define IDC_COLLISION_CAMERA            1125
#define IDC_GEOMETRY_SHATTERABLE        1126
#define IDC_SUFFIX_EDIT                 1126
#define IDC_GEOMETRY_NPATCH             1127
#define IDC_AFFECT_ALL_RADIO            1131
#define IDC_AFFECT_SELECTED_RADIO       1132
#define IDC_LOD_INDEX_EDIT              1133
#define IDC_LOD_INDEX_SPIN              1134
#define IDC_ASSIGN_COLLISION_BITS_CHECK 1135
#define IDC_ASSIGN_NAMES_CHECK          1137
#define IDC_COLLISION_PROJECTILE        1138
#define IDC_COPY_SPECULAR_DIFFUSE       1139
#define IDC_ASSIGN_PREFIX_CHECK         1139
#define IDC_COLLISION_VEHICLE           1139
#define IDC_MAPPING_ARGS_EDIT           1140
#define IDC_ASSIGN_SUFFIX_CHECK         1140
#define IDC_MAPPING0_ARGS_EDIT          1140
#define IDC_MAPPING1_ARGS_EDIT          1141
#define IDC_SHADER_DEFAULTS_BUTTON      1143
#define IDC_STATE_SLIDER                1145
#define IDC_CURRENT_SET_SLIDER          1146
#define IDC_CURRENT_SET_STATIC          1147
#define IDC_VERTEX_COLOR                1149
#define IDC_RESTORE_BUTTON              1150
#define IDC_MANUALAPPLY                 1151
#define IDC_SURFACE_TYPE_COMBO          1152
#define IDC_EXPORT_MESH_SMOOTH_CHECK    1153
#define IDC_LOCK_SETS                   1154
#define IDC_EXPORT_MESH_AABTREES        1154
#define IDC_TEXTURE_BUTTON              1155
#define IDC_EXPORT_MESH_MAT_TO_TEXTURE  1155
#define IDC_AMOUNT_EDIT                 1156
#define IDC_EXPORT_MESH_OPTIMIZE        1156
#define IDC_AMOUNT_SPIN                 1157
#define IDC_DAMREG_INDEX_EDIT           1161
#define IDC_DAMREG_INDEX_SPIN           1162
#define IDC_DIRECTORY                   1163
#define IDC_STAGE0UVCHAN_EDIT           1163
#define IDC_BROWSE                      1164
#define IDC_STAGE0UVCHAN_SPIN           1164
#define IDC_RECURSIVE                   1165
#define IDC_STAGE1UVCHAN_EDIT           1165
#define IDC_LOD_COUNT                   1166
#define IDC_STAGE1UVCHAN_SPIN           1166
#define IDC_LOD_OFFSET                  1167
#define IDC_LOD_AS_COPY                 1168
#define IDC_LOD_AS_INSTANCE             1169
#define IDC_LOD_AS_REFERENCE            1170
#define IDC_DAMAGE_COUNT                1171
#define IDC_DAMAGE_OFFSET               1172
#define IDC_DAMAGE_AS_COPY              1173
#define IDC_PS2_PRESET_COMBO            1173
#define IDC_DAMAGE_AS_INSTANCE          1174
#define IDC_COMPATIBLE                  1174
#define IDC_DAMAGE_AS_REFERENCE         1175
#define IDC_ALPHA_EDIT                  1175
#define IDC_A_COMBO                     1176
#define IDC_B_COMBO                     1177
#define IDC_EXPORT_STANDARD_MATERIALS   1177
#define IDC_C_COMBO                     1178
#define IDC_EXPORT_UTILITIES_GROUP      1178
#define IDC_D_COMBO                     1179
#define IDC_COMPRESS_ANIMATION_CHECK    1179
#define IDC_ALPHA_SPIN                  1180
#define IDC_ALPHA_SPIN2                 1181
#define IDC_REDUCE_ANIMATION_CHECK      1188
#define IDC_REDUCE_ANIMATION_COMBO      1190
#define IDC_ANIMATION_FPS_STATIC        1191
#define IDC_COMPRESS_ANIMATION_FLAVOR_COMBO 1192
#define IDC_MAX_TRANS_ERROR_EDIT        1193
#define IDC_MAX_ROT_ERROR_EDIT          1194
#define IDC_ANIM_COMPRESS_PROGRESS      1196
#define IDC_ANIM_LOG_RICHEDIT           1198
#define IDC_VIEWLOG_CHECK               1199
#define IDC_VALUE                       1200
#define IDC_LABEL                       1201
#define IDC_ALPHA_CHECKBOX              1204
#define IDC_DAZZLE_COMBO                1205
#define IDC_CREATE_SETTINGS_FLOATER     1208
#define IDC_RADIO1                      1212
#define IDC_HLOD_RADIO                  1212
#define IDC_RADIO2                      1213
#define IDC_COMPRESSION_SETTINGS        1213
#define IDC_ANIM_RADIO                  1213
#define IDC_RADIO3                      1214
#define IDC_MESH_RADIO                  1214
#define IDC_RADIO4                      1215
#define IDC_SKELETON_RADIO              1215
#define IDC_GROUP_BOX                   1216
#define IDC_RADIO5                      1217
#define IDC_TERRAIN_RADIO               1217
#define IDC_USE_SKELETON_CHECK          1217
#define IDC_RADIO6                      1218
#define IDC_ANIM_HLOD_RADIO             1218
#define IDC_REVIEW_LOG                  1219
#define IDC_ENABLE_SORT_LEVEL           1220
#define IDC_SORT_LEVEL                  1221
#define IDC_SORT_LEVEL_SPIN             1222
#define IDC_GRIDDIM_EDIT                1223
#define IDC_GRIDDIM_SPIN                1224
#define IDS_SKIN_CLASS_NAME             60011
#define IDS_SKIN_OBJECT_NAME            60012
#define IDS_SKIN                        60013
#define IDS_SKIN_PARAMETERS             60014
#define IDS_SKIN_INFO                   60015
#define IDS_BONE_INFLUENCE_PARAMS       60016
#define IDS_SOT2                        60017
#define IDS_SKELETON_PARAMETERS         60018
#define IDS_PICK_BONE_DIALOG_TITLE      60019
#define IDS_PICK_BONE_BUTTON_TEXT       60020
#define IDS_MULTIPLE_OBJECTS            60021
#define IDS_NO_OBJECT                   60022
#define IDS_SPECULAR_COLOR              60023
#define IDS_AMBIENT_COLOR               60024
#define IDS_EMISSIVE_COLOR              60027
#define IDS_MATERIAL_HINTS              60028
#define IDS_PSX_OPTIONS                 60029
#define IDS_UV_MAPPING                  60030
#define IDS_ENVIRONMENT_MAPPING         60031
#define IDS_PASS_COUNT                  60032
#define IDS_PASS_SETTINGS               60033
#define IDS_PUBLISH                     60034
#define IDS_DISPLAY                     60035
#define IDS_RESIZE                      60036
#define IDS_NO_MIPMAP                   60037
#define IDS_CLAMP_U                     60038
#define IDS_CLAMP_V                     60039
#define IDS_ALPHA_BITMAP                60040
#define IDS_SURFACE_TYPE                60041
#define IDS_DISPLACEMENT_MAP            60042
#define IDS_ALPHA_MODIFIER_CLASS        60043
#define IDS_PS2_GAMEMTL                 60044
#define IDS_PC_TO_PS2_MAT_CONVERTER     60045
#define IDS_NO_LOD                      60046
#define IDS_W3DUTILITY_SETTINGS         60047
#define IDS_W3DUTILITY_TOOLS            60048
#define IDS_GRIDSNAPMODIFIER            60049
#define IDS_GRIDSNAP_TITLE              60050
#define IDS_GRID_DIMENSION              60051

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1225
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
